/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 fordeverest.gltf 
Author: Asadawut.Kaewma (https://sketchfab.com/Asadawut.Kaewma)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/ford-everest-sport-2023-c37bec0353a94f90a3acbe09ceb3aecf
Title: Ford Everest Sport 2023
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/fordeverest/fordeverest.gltf');
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-0.777, 0.387, 1.519]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1.049}>
            <group position={[-0.106, -0.187, -0.11]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.mesh_1_2_black_0.geometry} material={materials.black} position={[0.847, 1.162, -0.002]} scale={0.007} />
            </group>
            <group position={[-0.007, 0, 0]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.Object002_rim_everest_0.geometry} material={materials.rim_everest} position={[0.748, 1.349, -0.002]} scale={0.007} />
            </group>
            <group rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.tyre_RF_tyre_0.geometry} material={materials.tyre} position={[0.027, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.012} />
            </group>
            <mesh geometry={nodes.mesh_1_1_chrome_0.geometry} material={materials.chrome} position={[-0.093, -0.001, 0]} rotation={[0.029, 0, 0]} />
            <mesh geometry={nodes.SUPRA_DISC_RF_supra_disc_0.geometry} material={materials.supra_disc} position={[0.032, 0, 0]} rotation={[Math.PI / 2, 1.571, 0]} scale={1.048} />
          </group>
        </group>
        <group position={[-0.777, 0.387, -1.31]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1.049}>
            <group position={[-0.106, -0.187, -0.11]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.mesh_1_004_black_0.geometry} material={materials.black} position={[0.847, 1.162, -0.002]} scale={0.007} />
            </group>
            <group rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.tyre_RF001_tyre_0.geometry} material={materials.tyre} position={[0.027, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.012} />
            </group>
            <group position={[-0.007, 0, 0]} rotation={[-Math.PI, 0, 0]}>
              <mesh geometry={nodes.Object003_rim_everest_0.geometry} material={materials.rim_everest} position={[0.748, 1.349, -0.002]} scale={0.007} />
            </group>
            <mesh geometry={nodes.SUPRA_DISC_RF001_supra_disc_0.geometry} material={materials.supra_disc} position={[0.032, 0, 0]} rotation={[Math.PI / 2, 1.571, 0]} scale={1.048} />
            <mesh geometry={nodes.mesh_1_003_chrome_0.geometry} material={materials.chrome} position={[-0.093, -0.001, 0]} rotation={[0.029, 0, 0]} />
          </group>
        </group>
        <group position={[0.777, 0.387, 1.519]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1.049}>
            <group position={[0.106, -0.21, -0.055]} rotation={[Math.PI / 4, 0, Math.PI]}>
              <mesh geometry={nodes.mesh_1_008_black_0.geometry} material={materials.black} position={[0.847, 1.162, -0.002]} scale={0.007} />
            </group>
            <group rotation={[Math.PI / 4, 0, -Math.PI]}>
              <mesh geometry={nodes.tyre_RF002_tyre_0.geometry} material={materials.tyre} position={[0.027, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.012} />
            </group>
            <group position={[0.007, 0, 0]} rotation={[Math.PI / 4, 0, Math.PI]}>
              <mesh geometry={nodes.Object004_rim_everest_0.geometry} material={materials.rim_everest} position={[0.748, 1.349, -0.002]} scale={0.007} />
            </group>
            <mesh geometry={nodes.SUPRA_DISC_RF002_supra_disc_0.geometry} material={materials.supra_disc} position={[-0.032, 0, 0]} rotation={[-Math.PI / 4, -1.571, 0]} scale={1.048} />
            <mesh geometry={nodes.mesh_1_007_chrome_0.geometry} material={materials.chrome} position={[0.093, 0, 0]} rotation={[-2.385, 0, -Math.PI]} />
          </group>
        </group>
        <group position={[0.777, 0.387, -1.31]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1.049}>
            <group position={[0.106, -0.21, -0.055]} rotation={[Math.PI / 4, 0, Math.PI]}>
              <mesh geometry={nodes.mesh_1_006_black_0.geometry} material={materials.black} position={[0.847, 1.162, -0.002]} scale={0.007} />
            </group>
            <group rotation={[Math.PI / 4, 0, -Math.PI]}>
              <mesh geometry={nodes.tyre_RF003_tyre_0.geometry} material={materials.tyre} position={[0.027, 0, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.012} />
            </group>
            <group position={[0.007, 0, 0]} rotation={[Math.PI / 4, 0, Math.PI]}>
              <mesh geometry={nodes.Object005_rim_everest_0.geometry} material={materials.rim_everest} position={[0.748, 1.349, -0.002]} scale={0.007} />
            </group>
            <mesh geometry={nodes.SUPRA_DISC_RF003_supra_disc_0.geometry} material={materials.supra_disc} position={[-0.032, 0, 0]} rotation={[-Math.PI / 4, -1.571, 0]} scale={1.048} />
            <mesh geometry={nodes.mesh_1_005_chrome_0.geometry} material={materials.chrome} position={[0.093, 0, 0]} rotation={[-2.385, 0, -Math.PI]} />
          </group>
        </group>
        <group position={[0.777, 0.387, 1.519]}>
          <mesh geometry={nodes.caliper002_Caliper_0.geometry} material={materials.Caliper} position={[0.037, 0.01, -0.013]} rotation={[-1.22, -0.037, 3.133]} scale={1.049} />
        </group>
        <group position={[0.777, 0.387, -1.31]}>
          <mesh geometry={nodes.caliper003_Caliper_0.geometry} material={materials.Caliper} position={[0.037, 0.01, -0.013]} rotation={[-1.22, -0.037, 3.133]} scale={1.049} />
        </group>
        <group position={[-0.777, 0.387, 1.519]}>
          <mesh geometry={nodes.caliper_Caliper_0.geometry} material={materials.Caliper} position={[-0.036, 0.002, -0.017]} rotation={[2.006, 0.037, -0.008]} scale={1.049} />
        </group>
        <group position={[-0.777, 0.387, -1.31]}>
          <mesh geometry={nodes.caliper001_Caliper_0.geometry} material={materials.Caliper} position={[-0.036, 0.002, -0.017]} rotation={[2.006, 0.037, -0.008]} scale={1.049} />
        </group>
        <mesh geometry={nodes.mesh_3_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_38_redglass_0.geometry} material={materials.redglass} position={[0, 1.661, -2.135]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_36_chrome_0.geometry} material={materials.chrome} position={[0, 0.97, 2.122]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_33_redglass_0.geometry} material={materials.redglass} position={[0, 0.661, -2.167]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_32_clearglass_0.geometry} material={materials.clearglass} position={[0, 1.097, -2.231]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_27_chrome_0.geometry} material={materials.chrome} position={[0, 1.661, -2.131]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_26_redglass_0.geometry} material={materials.redglass} position={[0, 1.145, -2.245]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_25_clearglass_0.geometry} material={materials.clearglass} position={[0, 0.989, 2.171]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.body_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_34_clearglass_0.geometry} material={materials.clearglass} position={[0, 1.107, -2.217]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_30_1_chrome_0.geometry} material={materials.chrome} position={[0, 0.664, 2.132]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_30_clearglass_0.geometry} material={materials.clearglass} position={[0, 0.663, 2.124]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_28_chrome_0.geometry} material={materials.chrome} position={[-1.007, 1.344, 0.655]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_35_chrome_0.geometry} material={materials.chrome} position={[1.007, 1.344, 0.655]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_16_black_0.geometry} material={materials.black} position={[0, 0.995, 2.265]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_15_black_0.geometry} material={materials.black} position={[-0.003, 0.911, -0.016]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_13_chrome_0.geometry} material={materials.chrome} position={[0, 1.009, 2.022]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_12_chrome_0.geometry} material={materials.chrome} position={[0, 0.99, 2.415]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_11_blue_0.geometry} material={materials.blue} position={[0, 1.129, 0.046]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_10_chrome_0.geometry} material={materials.chrome} position={[0, 1.363, 0.618]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_9_black_0.geometry} material={materials.black} position={[0, 1.484, -1.339]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_8_windows_glass_0.geometry} material={materials.windows_glass} position={[0, 1.471, -0.532]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_7_chrome_0.geometry} material={materials.chrome} position={[0, 1.066, -0.048]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_5_black_0.geometry} material={materials.black} position={[0, 0.962, -0.064]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_4_black_0.geometry} material={materials.black} position={[0, 0.657, -2.226]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_3_chrome_0.geometry} material={materials.chrome} position={[0, 0.857, -0.025]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_2_black_0.geometry} material={materials.black} position={[0, 1.115, -0.009]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.mesh_3_1_clearglass_0.geometry} material={materials.clearglass} position={[0, 0.939, -0.04]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object001_clearglass_0.geometry} material={materials.clearglass} position={[0, 1.083, 2.23]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object006_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object007_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object008_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object009_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object010_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object011_carpaint_0.geometry} material={materials.carpaint} position={[0, 1.114, -0.002]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object012_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object013_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object014_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object015_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object016_black_0.geometry} material={materials.black} position={[0.001, 1.074, 0.02]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
        <mesh geometry={nodes.Object017_light_0.geometry} material={materials.light} position={[0, 0.857, -0.025]} rotation={[-Math.PI / 2, 0, 0]} scale={0.008} />
      </group>
    </group>
  )
}

useGLTF.preload('/fordeverest.gltf')
