/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 bmwM5.gltf 
Author: Outlaw Games™ (https://sketchfab.com/Outlaw_Games)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/2018-bmw-m5-30fa0c4408bc43be8c3a67c51fcc6184
Title: 2018 BMW M5
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/models/bmwM5/bmwM5.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group scale={0.01}>
          <mesh geometry={nodes.Object_8.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <group position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]}>
            <mesh geometry={nodes.Object_14.geometry} material={materials.bM_Opaque_RubberRough_Max1} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.bM_Engine_Max1} />
            <mesh geometry={nodes.Object_20.geometry} material={materials.bM_CarPaint_Max1} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.bM_CarPaint_Trim_CarbonA_Max1} />
            <mesh geometry={nodes.Object_24.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} />
            <mesh geometry={nodes.Object_26.geometry} material={materials.bM_Chassis_Max1} />
          </group>
          <mesh geometry={nodes.Object_29.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.bM_Glass_WindowSurroundFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.bM_Glass_WindowSurroundFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_53.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_59.geometry} material={materials.bM_Glass_WindowSurroundFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.bM_Glass_WindowSurroundFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_65.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.bM_Interior_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <group position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]}>
            <mesh geometry={nodes.Object_71.geometry} material={materials.bM_Interior_Max1} />
            <mesh geometry={nodes.Object_73.geometry} material={materials.emis} />
          </group>
          <mesh geometry={nodes.Object_76.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_79.geometry} material={materials.bM_Opaque_ChromeSmooth_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_85.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_91.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_97.geometry} material={materials.bM_LightGlassNormal_OuterRed_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.bM_LightGlassNormal_Clear_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_103.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_109.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_112.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_115.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_121.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_124.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_127.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_130.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_133.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials.bM_LightGlass_Orange_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_139.geometry} material={materials.bM_GrilleA_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_145.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_151.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.bM_CarPaint_Trim_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_157.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_163.geometry} material={materials.bM_LightGlass_Red_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_166.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_169.geometry} material={materials.bM_Interior_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_175.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.bM_Opaque_RubberRough_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_181.geometry} material={materials.bM_Interior_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_187.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.bM_Opaque_RubberRough_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_193.geometry} material={materials.bM_Opaque_NickelRough_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.bM_Opaque_NickelSmooth_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_199.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_205.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_211.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_217.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_220.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_223.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_229.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_235.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.bM_Interior_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_241.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_244.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_247.geometry} material={materials.bM_Opaque_RubberRough_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_250.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_253.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_259.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_265.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_271.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_277.geometry} material={materials.bM_LightGlassNormal_Clear_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.bM_LightGlassNormal_Clear_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_283.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_289.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.bM_LightGlassNormal_Clear_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_295.geometry} material={materials.bM_LightGlassNormal_Clear_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.bM_Engine_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_301.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_307.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_313.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_319.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_325.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_328.geometry} material={materials.bM_GlassOpaque_Mirror_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_331.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_337.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_343.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_349.geometry} material={materials.bM_GlassOpaque_Mirror_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_352.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_355.geometry} material={materials.bM_Opaque_PaintSolidBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_358.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_361.geometry} material={materials.bM_Opaque_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_364.geometry} material={materials.bM_Glass_WindowFront_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_367.geometry} material={materials.bM_CarPaint_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_370.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_373.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_376.geometry} material={materials.bM_Chassis_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_379.geometry} material={materials.bM_Opaque_PlasticRoughBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_382.geometry} material={materials.bM_CarPaint_Trim_PlasticSmoothBlack_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_385.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_388.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_391.geometry} material={materials.bM_LightGlassNormal_OuterRed_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_394.geometry} material={materials.bM_LightBucket_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_397.geometry} material={materials.bM_Badge_Max1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <mesh geometry={nodes.Object_400.geometry} material={materials.bM_LightGlassNormal_OuterRed_Low1} position={[0, 0.201, 0.132]} rotation={[0.011, 0, 0]} />
          <group position={[0.763, 0.351, 1.622]} rotation={[0, 0, 0.026]}>
            <mesh geometry={nodes.Object_483.geometry} material={materials.bMAT_Details_Hub1} position={[0.04, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_486.geometry} material={materials.bMAT_Details_Disk1} position={[0.04, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_489.geometry} material={materials.bM_Rim_Main_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_492.geometry} material={materials.bM_Rim_NoTint_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_495.geometry} material={materials.bM_RimBadge_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_498.geometry} material={materials.bM_Rim_Secondary_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_405.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_408.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_411.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_414.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_417.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_420.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_423.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_426.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_429.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_432.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_435.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_438.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_441.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_444.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_447.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_450.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_453.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_456.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_459.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_462.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_465.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_468.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_471.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_474.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_477.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_480.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
          </group>
          <group position={[-0.763, 0.351, 1.622]} rotation={[Math.PI, 0, -3.115]}>
            <mesh geometry={nodes.Object_583.geometry} material={materials.bMAT_Details_Disk1} position={[0.04, 0, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_586.geometry} material={materials.bMAT_Details_Hub1} position={[0.04, 0, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_589.geometry} material={materials.bM_Rim_Main_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_592.geometry} material={materials.bM_Rim_NoTint_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_595.geometry} material={materials.bM_RimBadge_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_598.geometry} material={materials.bM_Rim_Secondary_Max1} position={[0.056, 0, 0]} />
            <mesh geometry={nodes.Object_502.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_505.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_508.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_511.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_514.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_517.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_520.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_523.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_526.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_529.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_532.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_535.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_538.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_541.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_544.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_547.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_550.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_553.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_556.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_559.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_562.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_565.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_568.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_571.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_574.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_577.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_580.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
          </group>
          <group position={[0.739, 0.36, -1.373]} rotation={[0, 0, 0.017]}>
            <mesh geometry={nodes.Object_680.geometry} material={materials.bMAT_Details_Hub1} position={[0.05, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_683.geometry} material={materials.bMAT_Details_Disk1} position={[0.05, 0, 0]} rotation={[0, -Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_686.geometry} material={materials.bM_Rim_Main_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_689.geometry} material={materials.bM_Rim_NoTint_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_692.geometry} material={materials.bM_RimBadge_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_695.geometry} material={materials.bM_Rim_Secondary_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_602.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_605.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_608.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_611.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_614.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_617.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_620.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_623.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_626.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_629.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_632.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_635.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_638.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_641.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_644.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_647.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_650.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_653.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_656.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_659.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_662.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_665.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_668.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_671.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_674.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_677.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
          </group>
          <group position={[-0.739, 0.36, -1.373]} rotation={[Math.PI, 0, -3.124]}>
            <mesh geometry={nodes.Object_777.geometry} material={materials.bMAT_Details_Hub1} position={[0.05, 0, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_780.geometry} material={materials.bMAT_Details_Disk1} position={[0.05, 0, 0]} rotation={[0, Math.PI / 2, 0]} scale={[0.012, 0.012, 0.009]} />
            <mesh geometry={nodes.Object_783.geometry} material={materials.bM_Rim_Main_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_786.geometry} material={materials.bM_Rim_NoTint_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_789.geometry} material={materials.bM_RimBadge_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_792.geometry} material={materials.bM_Rim_Secondary_Max1} position={[0.067, 0, 0]} />
            <mesh geometry={nodes.Object_699.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_702.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_705.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_708.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_711.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_714.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_717.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_720.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_723.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_726.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_729.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_732.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_735.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_738.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_741.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_744.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_747.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_750.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_753.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_756.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_759.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_762.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_765.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_768.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_771.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
            <mesh geometry={nodes.Object_774.geometry} material={materials.BMW_M5CSRewardRecycled_2022_Wheel1A_3D_3DWheel1A_Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bmwM5.gltf')
